### ISSUE TITLE
Resource not released as expected

### ISSUE THREAD

**Issue by loathwine** [7mind/izumi#1138]
Hi, I think I've found a bug. I was upgrading ZIO/distage versions in my project and one of my tests completed but the testrunner got stuck afterwards. I have included a more minimal example using distage version `0.10.16` and ZIO `1.0.0-RC21-2`. 
I have two tests, one using a ZManaged directly and one using DIResource as a wrapper. The one using DIResource does not seem to release the resource.

This worked in earlier versions using distage `0.10.3-M2` with zio `1.0.0-RC18-2`. Is this a bug or have I done something incorrectly?

```
import distage.ModuleDef
import izumi.distage.effect.modules.ZIODIEffectModule
import izumi.distage.model.definition.DIResource
import izumi.distage.plugins.PluginConfig
import izumi.distage.testkit.TestConfig
import izumi.distage.testkit.scalatest.DistageBIOSpecScalatest
import logstage.LogBIO
import zio._
import zio.stream.ZStream

class DIResourceTest extends DistageBIOSpecScalatest[IO] {
  case class Result(s: String)
  def makeResource(logger: LogBIO[IO]): ZManaged[Any, Nothing, Result] =
    for {
      queue <- ZQueue.unbounded[Unit].toManaged(_ => logger.debug("Releasing queue"))
      _ <- ZStream
        .fromQueue(queue) // Can also skip the queue and use ZStream.never
        .runDrain
        .forkManaged
        .onExit(exit => logger.debug(s"Consumer stream $exit"))
    } yield Result("resource acquired")

  override def config: TestConfig = TestConfig(
    pluginConfig = PluginConfig.empty,
    moduleOverrides = new ModuleDef {
      include(ZIODIEffectModule)
      make[LogBIO[IO]].from(LogBIO.fromLogger[IO] _)
      make[Result].fromResource((logger: LogBIO[IO]) => DIResource.fromZIO(makeResource(logger)))
    },
    configBaseName = "diresource-test",
    debugOutput = true,
  )

  "resource" should {
    "be released properly with DIResource" in { (res: Result, log: LogBIO[IO]) =>
      for {
        _ <- log.debug(s"distage using resource $res")
      } yield ()
    }

    "be released properly with ZManaged" in { (log: LogBIO[IO]) =>
      for {
        _ <- makeResource(log).use(res => log.debug(s"ZManaged using $res"))
      } yield ()
    }
  }
}
```

Any help is appreciated!

**Comment by neko-kai** [comment]
@Edvin-san 
This happens because of "interruption inheritance" in ZIO.
In DIResource the entire `acquire` section is inside `.uninterruptible`, but .forkManaged applies the outer uninterruptibility section to the new fork, which becomes uninterruptible and now cannot be interrupted by `DIResource.release`

**Comment by neko-kai** [comment]
The way to fix that might be to apply the same strategy as ZManaged itself - instead of forcibly wrapping all `acquire`s in `.uninterruptible`, let acquire be interruptible and set uninterruptibility within it manually. But this may not work that well with class-based DIResource's, we may possibly need a super-type above DIResourceBase, e.g. DIResourceBaseInterruptible which would be very ugly indeed

**Comment by loathwine** [comment]
This is still an issue in 1.0.0, although it is not really distage-specific. A workaround (provided by @neko-kai) is to explicitly make the `ZManaged` in an interruptible scope:
```scala
def interruptibleZManaged[R, E, A](zmanaged: ZManaged[R, E, A]): ZManaged[R, E, A] =
    ZManaged(zmanaged.zio.interruptible)
```
