### ISSUE TITLE
LogStage vs Scribe

### ISSUE THREAD

**Issue by darkfrog26** [7mind/izumi#382]
I'm the author of the Scribe logging library and I just recently noticed LogStage.  I was wondering if you'd be interested in discussing the differences in our libraries to see if a possible joining of forces was in the best interest of both of our projects?

**Comment by pshirshov** [comment]
Hi, 

So, at the moment our library is all about zero-cost structural logging and structure extraction.

So we may turn `s"message: $value"` into both `{"value": "xxx", "@template": "message: ${value}", "@id": "deadbeef"}` and `"message: xxx"`

As well we have rich DSL allowing us to alter representations: `message: ${value -> "visible name"}`, etc.

What we have in common - both our libraries are extracting file/line info and have method level granularity.

We both have slf4j interop. At the moment we don't have anything except of slf4j integration while you integrate with other stuff as well.

Re: performance: till we moment we didn't pay _too much_ attention to that aspect, though the library behaves well in high loaded production. It has no hotspots. Though I guess yours one should be more optimal as per you are concerned about it, have benchmarks, etc. Our only benchmarks are our production and JProfiler.  

Also our framework is inteded to be used together with a DI framework (and of course we provide [DIStage](https://izumi.7mind.io/v0.6.0-SNAPSHOT/doc/distage/index.html) integration), so we have no singletons (except of the one we need for Slf4J integration) and we don't provide any logging mixin like your `Logging`. So, we are non-invasive and we are promoting SOLID code.

The conclusion is: we have lot more advanced API and we are ergonomic-oriented, your stuff is more mature and has more integrations.

Also you may look at our slides on logstage [here](https://github.com/7mind/slides/blob/master/01-logstage/target/logstage.pdf)

> to see if a possible joining of forces was in the best interest of both of our projects?

We wouldn't mind. We've implemented this because there are no alternatives available, structural logging is very important for our flows. Though it still takes time to maintain.

**Comment by darkfrog26** [comment]
It looks as though you have fleshed out several areas that Scribe has not.  Scribe has gained a lot of visibility recently and is pretty widely used now, but there are very few developers touching the code.  I'm very interested in pushing the envelope for logging to make it the best solution available.  I think there are quite a few areas that LogStage could influence Scribe for the better if you're interested in collaboration.

As I'm sure you've seen, Scribe purports to be the fastest logging library in the world.  This is done by a heavy focus on performance tuning and testing.  This seems to be something your team cares about as well.

With regard to structured logging, we do support that with our Logstash module, but it's not something that is designed for more general usage like yours though I can see the benefit.

Logging in Scribe is very flexible. If you look at any of the examples, you'll see that the mix-in isn't the recommended way to do logging anymore.  To log in Scribe you need to just:

```scala
scribe.info("So easy!")
```

The Macros deal with rest so you don't have to mix-in anything or even import anything.  It makes it trivial to add and remove logging without any other boilerplate code.

The extraction of variables from the Macro in LogStage is clever, I like that!

**Comment by darkfrog26** [comment]
Ultimately, I don't know if we'll end up with exclusive goals that keep us from working together, but I do see that one great logging library in Scala would be far more appealing than several that do a few things well.

**Comment by pshirshov** [comment]
> you're interested in collaboration.

We are. How would you see this? For example you may take our core part - the structural extractor, keeping our credentials. As well we may publish it as a separate micro library.

> As I'm sure you've seen, Scribe purports to be the fastest logging library in the world. This is done by a heavy focus on performance tuning and testing. This seems to be something your team cares about as well.

Yup, though as I said before - performance is not our critical concern. We are profiling and taking care of hotspots but aren't trying to achieve top perf. Also sometimes we are trading memory for efficiency - like ideally we should use a prefix tree to get logger configurations by name but at the moment we use just a concurrent hashmap. In case someone complains about that - we may address that but at the moment it works very well and we are limited on human resources - so we are avoiding premature optimization.

> With regard to structured logging, we do support that with our Logstash module, but it's not something that is designed for more general usage like yours though I can see the benefit.

From what I can understand it's different from our approach. Usually it's hard to write code emitting structured logs - in our case you get that for free.


> Logging in Scribe is very flexible. If you look at any of the examples, you'll see that the mix-in isn't the recommended way to do logging anymore. To log in Scribe you need to just:

Though you still have it. It's not a big deal to implement a mixin, but we are restricting our users intentionally.


> ```scala
> scribe.info("So easy!")
> ```

This assumes to be a singleton? We are trying to avoid such things at all costs - they don't work well with isolated classloaders, under OSGi, etc.

> The Macros deal with rest so you don't have to mix-in anything or even import anything. It makes it trivial to add and remove logging without any other boilerplate code.

Mm, but you aren't modifying constructor signatures, right? Would your code work with DI?
 
> The extraction of variables from the Macro in LogStage is clever, I like that!
Thank you. The idea itself is so simple that I've always been feeling frustrated that noone implemented it.

By the way, look at our DI and other stuff. It's full of amazing an unique ideas :)

**Comment by pshirshov** [comment]
> Ultimately, I don't know if we'll end up with exclusive goals that keep us from working together, 

We have only one goal - productivity at all costs. So, in general we wouldn't hesitate to start a separate project nor accepting you as a contributor nor sharing our code/ideas with your library nor cross-promoting each other.

What we need from a logging framework:

1. Structure
2. To be and promote SOLID code
3. DI and classloader safety

So, in case items (2) and (3) are aligned with your goals - why not to cooperate. 

> but I do see that one great logging library in Scala would be far more appealing than several that do a few things well.

At one hand you are right. At the other hand - different people have different opinions. For us a mixin is an unacceptable evil, for example. As well - logging is a very opinionated subject, our nor yours views may not work for someone. Like we are fine to emit a lot of code but some people (I guess those who write for smartcards) may be unable to afford that. 

I agree that one great library would be better than two atmost good ones. But I don't want to try to push logging into standard library/etc - it would inevitably become one more shitty thing in order to satisfy all the users.

**Comment by darkfrog26** [comment]
The `scribe` package-level methods (ex. `scribe.info`) utilize `Logger.apply` to get the `Logger` instance via class name (see: https://github.com/outr/scribe/blob/master/core/shared/src/main/scala/scribe/package.scala#L10), which is itself dependency-injection support.

In later versions of Scribe we've been moving further from the concept of a `message: String` toward more structured objects for better integration with more advanced use-cases (see: https://github.com/outr/scribe/blob/master/core/shared/src/main/scala/scribe/LogRecord.scala).

In the upcoming Scribe 2.7, we'll be taking this to new heights with the `StylizedMessage` object that allows generic coloring and other stylization for use where supported (ANSI, HTML, console.log, etc.)

While I can appreciate your enforcement of good programming paradigms, I disagree that a library like logging should be overly opinionated.  I prefer to offer what I consider to be the "best path", while still offering legacy or popular mechanisms so developers can choose their preferred conventions.

I believe the `Structure` is the only thing Scribe is really lacking.  If you'd be interested in contributing functionality for that, the "productivity at all costs" could be solved by migrating to Scribe and reducing the coding burden on your team having to support a logging library.

**Comment by pshirshov** [comment]
> The `scribe` package-level methods (ex. `scribe.info`) utilize `Logger.apply` to get the `Logger` instance via class name (see: https://github.com/outr/scribe/blob/master/core/shared/src/main/scala/scribe/package.scala#L10), which is itself dependency-injection support.

Let me criticise a bit:

```
package object scribe extends LoggerSupport {
  // this shouldn't be here. It's odd and ugly, it should appear at sink level only
  lazy val lineSeparator: String = System.getProperty("line.separator")

  protected[scribe] var disposables = Set.empty[() => Unit]

  // logger itself is an overburdened case class having a lot of responsibilities. 
  // I'm not sure why you call it "DI support" - it would be inconvenient to produce 
  //  Loggers with a DI framework. 
  //  For example you are bearing modifiers there and relying on default parameters
  override def log[M](record: LogRecord[M]): Unit = Logger(record.className).log(record)
```

I should mention that we aren't instantiating at runtime and a typical app has just one instance of `IzLogger`. Our macro wires log calls with all the missing information. I guess in case we wish to achieve _top perf_ this approach may be more viable as per it assumes _less_ instantiations (though we still do a lot in our sinks).

> In later versions of Scribe we've been moving further from the concept of a `message: String` toward more structured objects for better integration with more advanced use-cases (see: https://github.com/outr/scribe/blob/master/core/shared/src/main/scala/scribe/LogRecord.scala).

We have a similar thing.

> In the upcoming Scribe 2.7, we'll be taking this to new heights with the `StylizedMessage` object that allows generic coloring and other stylization for use where supported (ANSI, HTML, console.log, etc.)

We have similar thing as well.

> While I can appreciate your enforcement of good programming paradigms, I disagree that a library like logging should be overly opinionated. I prefer to offer what I consider to be the "best path", 

What I mean is: different people see different best paths. A library which would work for almost all the people would be a shit almost inevitably. IMHO.

> while still offering legacy or popular mechanisms so developers can choose their preferred conventions.

I don't think a logger should support all the possible ways of log emitting. Maybe just as a separate `legacy-compat` layer.

> I believe the `Structure` is the only thing Scribe is really lacking. 

Yup, right. Though I think you still may improve the whole design a lot an strip unrequired things out of the library core. And make sure that it works well under OSGi, isolated classloaders, etc.

> If you'd be interested in contributing functionality for that, the "productivity at all costs" could be solved by migrating to Scribe and reducing the coding burden on your team having to support a logging library.

We may. Though I'm not sure _when_ may we do it - we are kinda overbooked atm. Though yes, we may. We are at the stage when we are hitting limits of our capacity and need to grow as a company but we can't grow because our cash flow isn't enough to hire more people. We need more customers to grow and we need to grow to satisfy customers )

**Comment by darkfrog26** [comment]
I certainly understand.  You raise some very valid points of improvement in Scribe, but they just haven't been areas that have been very important for me or Scribe's users in the past.  I would welcome most of these concepts into Scribe.  DI is something I try to avoid unless absolutely necessary as it tends to muck up the waters, but I recognize there are many use-cases where it's a necessary evil.

When you are ready to consider a migration I'd be happy to work with you to make sure that Scribe is a smooth path and has all the functionality you desire.  In the meantime, if you get around to extracting the Structure functionality into an independent module, I'd be very interested in incorporating it into Scribe as I think there are some very good ideas there.

**Comment by pshirshov** [comment]
> but I recognize there are many use-cases where it's a necessary evil.

Proper DI is not an evil, its a huge productivity boost, btw. Please look at our one, it has first class scala typesystem support and based on a very interesting theory so it solves some problems people get used to consider unsolvable.

Re migration: I may help you to pull out the structure extractor in foreseeable future, I think. The rest-refactorings and adressing design issues requires a lot of time, so it can be done later.

Also I would ask you to promote us/our stack a bit :3

**Comment by neko-kai** [comment]
@darkfrog26 

> In the meantime, if you get around to extracting the Structure functionality into an independent module, I'd be very interested in incorporating it into Scribe as I think there are some very good ideas there.

It's already a separate module with no dependencies, you can just depend on it directly, or copypaste it. https://github.com/pshirshov/izumi-r2/tree/develop/logstage/logstage-api-base-macro
