### ISSUE TITLE
Implement type projection tags

### ISSUE THREAD

**Issue by pshirshov** [7mind/izumi#433]

**Comment by neko-kai** [comment]
Related: #374

**Comment by neko-kai** [comment]
We should probably remove free term singleton equality heuristics as part of this, and restrict pdts/projections to static objects only

**Comment by neko-kai** [comment]
Implementation involves adding a case for `TypeRef` here:
https://github.com/pshirshov/izumi-r2/blob/develop/fundamentals/fundamentals-reflection/src/main/scala/com/github/pshirshov/izumi/fundamentals/reflection/TagMacro.scala#L66
and the associated logic for handling the prefix.

**Comment by neko-kai** [comment]
The only way to get into a situation where a type prefix may need resolution is to use type projection on a type parameter, as in:

```scala
class Path {
  type Child
}

def getTag[A <: Path: Tag]: Tag[A#Child] = Tag[A#Child]
```

However, type parameters CANNOT be used in prefixes starting from Scala 3, only concrete class types can. So `Path#Child` is ok, but `A#Child` is illegal - https://dotty.epfl.ch/docs/reference/dropped-features/type-projection.html

I think since this form is deprecated anyway, it's not a good idea to use – and we may not really need to support it either.
