### ISSUE TITLE
Initialization of Logstage during testing with ScalaTest

### ISSUE THREAD

**Issue by nartamonov** [7mind/izumi#544]
I have a few ScalaTest specs with integration tests inside. Some of the tests use third-party libs which output useful logs via Slf4j. Currently before running any tests I need to configure Logstage, otherwise part of the logs will be omitted. I use something like:

```scala
trait DependentOnLogger {
  self: Suite =>

  val logger: IzLogger = /* ... */
  StaticLogRouter.instance.setup(logger.router)
}

class SomeSpec extends FunSpec with DependentOnLogger {
  it("should pass") {
    someMethodWhichOutputsSlf4jLogs()
  }
}
```

Althought it works, it seems rather inconvenient because I need to mix-in `DependentOnLogger` in every spec and can easily forget to do it.

May be it could be imporoved someway?

**Comment by neko-kai** [comment]
Hi, @nartamonov !

We can change the `StaticLogRouter` defaults, so that more messages are printed without configuration - see https://github.com/7mind/izumi/pull/547 (print to stdout, lower threshold from `warn` to `info`)

Besides that, I don't think much can be done, without introducing e.g. a special configuration file or system properties for `StaticLogRouter` that it'll read at startup. The reason is that classes are only loaded when they are referenced, so any static variables that mutate the `StaticLogRouter` would have to also be referenced from your code somewhere to be loaded - the same applies to Scala `object`s.

I think the pattern you use here is completely fine – it's completely OK to declare your own Scalatest traits with project-specific configurations. You could enhance the pattern by bundling your configurations into a default Spec trait that you use everywhere:

```scala
trait MySpec extends FunSpec with DependentOnLogger
```

That way you can't forget to mix it in if you always use it as base trait, instead of Scalatest's `FunSpec`, `WordSpec`, etc.

**Comment by neko-kai** [comment]
@nartamonov Has your issue being addressed by latest changes? Current release is now [`0.8.6`](https://github.com/7mind/izumi/releases/tag/v0.8.6)

**Comment by neko-kai** [comment]
Closing due to lack of response...
