### ISSUE TITLE
logstage: concatenation of Message results in trimmed spaces at the beginning

### ISSUE THREAD

**Issue by an-tex** [7mind/izumi#983]
```scala
import izumi.logstage.api.IzLogger
import izumi.logstage.api.Log.Level.Debug
import izumi.logstage.api.Log.Message
import izumi.logstage.sink.ConsoleSink

val log = IzLogger(Debug, Seq(ConsoleSink.SimpleConsoleSink))
val a = 0
val b = 1
val c = 2
val d = 3

val message = Message(s"$a") +
  Message(s" $b") +
  Message(s" $c") +
  Message(s" $d")

log.log(Debug)(message)
```
Expected output: `a=0 b=1 c=2 d=3`
Actual output: `a=0b=1 c=2d=3 `

There's no space between arg groups of two, this pattern continues for more concatenations. Adding parenthesis doesn't help.

Putting the spaces to the end
```scala
val message = Message(s"$a ") +
  Message(s"$b ") +
  Message(s"$c ") +
  Message(s"$d ")
```

results in `a=0 b=1c=2 d=3`

Having spaces around leads to the expected output:
```scala
val message = Message(s"$a ") +
  Message(s" $b ") +
  Message(s" $c ") +
  Message(s" $d")
```
-> `a=0 b=1 c=2 d=3 ` (except there seems to be an extra space after d)

I guess it's an issue around the concatenation of the StringContexts, but I couldn't quite nail it down.

Related: https://github.com/7mind/izumi/issues/975

**Comment by an-tex** [comment]
Ok it get's even stranger:
```scala
val message = Message(s"$a/a ") +
  Message(s"$b/b ") +
  Message(s"$c/c ") +
  Message(s"$d/d")
```
results in `a=0/a b=1c=2/b d=3`

**Comment by neko-kai** [comment]
@an-tex 
Yes, seems like this happens because of breakage of StringContext's invariants, REPL example:

```scala
scala> implicit class R(s: StringContext) { def ctx(interpolations: Any*): StringContext = s }
defined class R

scala> val a = ctx" ${1}"
a: StringContext = StringContext(ArraySeq( , ))

scala> val b = ctx" ${2}"
b: StringContext = StringContext(ArraySeq( , ))

scala> val newCtx = StringContext(a.parts ++ b.parts: _*)
newCtx: StringContext = StringContext(ArraySeq( , ,  , ))

scala> newCtx.checkLengths(Seq(1, 2))
java.lang.IllegalArgumentException: wrong number of arguments (2) for interpolated string with 4 parts
  at scala.StringContext$.checkLengths(StringContext.scala:408)
  at scala.StringContext.checkLengths(StringContext.scala:62)
  ... 28 elided
```

`checkLengths` doc states:
```
  /** Checks that the length of the given argument `args` is one less than the number
   *  of `parts` supplied to the enclosing `StringContext`.
   *  @param `args` The arguments to be checked.
   *  @throws IllegalArgumentException  if this is not the case.
   */
```

That is, an interpolation like `s" $a"` produces a StringContext call `StringContext(parts = " ", "").s(interpolations = a)`

Note how in `parts` there's no markers as to where the `a` in `interpolations` should be placed, it's always assumed that interpolations are placed in-between parts. If the interpolation happens at the end of the string an empty "" part is generated.

That means there is always a part, even if empty, at the start and at the end of any `StringContext`,

so to fix this, instead of concatenating the parts naively in [this code](https://github.com/7mind/izumi/blob/790c2e914be93962e4cb56c4e50eb41117d1ab19/logstage/logstage-core/src/main/scala/izumi/logstage/api/Log.scala#L160), you should also merge together the last part of left StringContext with the head part of the next StringContext to ensure that as before, the length of parts is -1 from the length of interpolations and the interpolations are placed in between parts.
Would you be open to making a PR fixing this? Thanks!

**Comment by an-tex** [comment]
Thanks for the clarification, I'll take care of it!
